### ISSUE TITLE
Kotlin integration?

### ISSUE THREAD

**Issue by pranav-asthi** [wl-online-payments-direct/sdk-client-android#1]
How to implement this sdk in a Kotlin project.There is no example app found in this repo

**Comment by worldline-direct-support-team** [comment]
Hello Pranav,

Thank you for your question. We do not currently offer an example in Kotlin. However, we do have an example in Java that you can find here: https://github.com/wl-online-payments-direct/sdk-client-android-example 

The way the SDK should be used, is the same for Java and Kotlin. Hopefully the Java example can help you along.

Kind regards,
The Worldline support team
