### ISSUE TITLE
Get payment product api error

### ISSUE THREAD

**Issue by AlbertoHdzDev** [wl-online-payments-direct/sdk-client-android#2]
Hello
I am implementing the SDK for Android to make payments with Google Pay. SDK version 2.3.2 and Development Environment.
First, I create the "Session" object, then the "PaymentContext" and finally, I call the "getPaymentProduct" method. 
The SDK Log is Success, but the SDK callback is going to "OnApiError". What is going wrong?
I attach  code and Log screenshots.
Thanks and best regards.

![Code](https://github.com/user-attachments/assets/07fcbb6a-b103-4e2b-9e8c-3d601fd6e30f)
![LogResponse](https://github.com/user-attachments/assets/e9b4cb34-3b43-450e-862e-c31ce8307e2d)
![ApiError](https://github.com/user-attachments/assets/1997fa1f-62ca-4e42-b1e1-4b34e0a91c5e)

**Comment by worldline-direct-support-team** [comment]
Hi AlbertoHdzDev,

According to the [Google Pay API docs](https://developers.google.com/pay/api/android/guides/setup), the following should be added to your AndroidManifest:
```
<meta-data
            android:name="com.google.android.gms.wallet.api.enabled"
            android:value="true" />
```

Can you please confirm whether this resolves your issue?

**Comment by AlbertoHdzDev** [comment]
Yes! I confirm that adding the code solves the problem.
Thank you very much for the help!
